name       : plasma-desktop-branding
version    : 1
release    : 12
source     :
    - git|https://github.com/getsolus/plasma-desktop-branding.git : 819140430d8736622039df26673710706cd5a5e6
license    : GPL-2.0-or-later
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - solus-artwork
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
