name       : plasma-desktop-branding
version    : '3.1'
release    : 31
source     :
    - git|https://github.com/getsolus/plasma-desktop-branding.git : 0c095209d0f9b047897b4b90319c4aa140586681
license    : Apache-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-light-cursor-theme
    - breeze-gtk-theme
    - font-clear-sans-ttf
    - solus-artwork-plasma
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
