name       : plasma-desktop-branding
version    : '3'
release    : 22
source     :
    - git|https://github.com/getsolus/plasma-desktop-branding.git : dae24b8c8b9d2d4e34d9273730718f733cf92c3f
license    : Apache-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - font-clear-sans-ttf
    - solus-artwork-plasma
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
