name       : plasma-desktop-branding
version    : 1
release    : 11
source     :
    - git|https://dev.getsol.us/source/plasma-desktop-branding-src.git : a6093baf617dbaa7344de4ac1a8d48137f3e8c7f
license    : GPL-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - solus-artwork
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
