name       : plasma-desktop-branding
version    : 1
release    : 6
source     :
    - git|https://github.com/solus-project/plasma-desktop-branding.git : da2cf1b81f64032326955bc99ea8812e6aab5f1a
license    : GPL-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - solus-artwork
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
