name       : plasma-desktop-branding
version    : '2'
release    : 18
source     :
    - https://github.com/getsolus/plasma-desktop-branding/archive/v2.tar.gz : b9d8c34ccc3c62c779965656997f500fc7902400810b54e369da1f98fb88dedc
license    : Apache-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - font-clear-sans-ttf
    - solus-artwork-plasma
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
