name       : plasma-desktop-branding
version    : 1
release    : 4
source     :
    - git|https://github.com/solus-project/plasma-desktop-branding.git : 789543c4d2a743673dd1774041ecae6492bddd7e
license    : GPL-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - solus-artwork
patterns   :
    - livecd :
        - /usr/share/sddm
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
