name       : plasma-desktop-branding
version    : 1
release    : 2
source     :
    - git|https://github.com/solus-project/plasma-desktop-branding.git : d0868e327416b2605cc9bb49c1e826d1bfdcc96c
license    : GPL-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - solus-artwork
patterns   :
    - livecd :
        - /usr/share/sddm
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
