name       : plasma-desktop-branding
version    : 1
release    : 15
source     :
    - git|https://github.com/getsolus/plasma-desktop-branding.git : 8b84bff9e8c058d7dfbee0cf8159907716a16333
license    : GPL-2.0-or-later
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - font-clear-sans-ttf
    - solus-artwork-plasma
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
