name       : plasma-desktop-branding
version    : '3.2'
release    : 64
source     :
    - git|https://github.com/getsolus/plasma-desktop-branding.git : 2f5b11a401fed456f6335c158c1d9801c87ba513
license    :
    - Apache-2.0
    - LGPL-2.0-only # layout-template
summary    : Defaults for the Plasma Desktop
component  :
    - desktop.kde.core
    - livecd : desktop.kde
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-light-cursor-theme
    - breeze-gtk-theme
    - font-clear-sans-ttf
    - solus-artwork-plasma
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
        - /usr/share/glib-2.0/schemas/50_plasma_livecd.gschema.override
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
