name       : plasma-desktop-branding
version    : 1
release    : 1
source     :
    - git|https://github.com/solus-project/plasma-desktop-branding.git : 9dfa504be35b4a7fd11c3a2f28bfdb359255df2b
license    : GPL-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - papirus-icon-theme
    - solus-artwork
patterns   :
    - livecd :
        - /usr/share/sddm
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
