name       : plasma-desktop-branding
version    : '3.0'
release    : 25
source     :
    - https://github.com/getsolus/plasma-desktop-branding/releases/download/3.0/plasma-desktop-branding-3.tar.xz : d59186e8a25b4f55e6c0620264addde39e07b6724aed812d2e4814737fad2a1f
license    : Apache-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - font-clear-sans-ttf
    - solus-artwork-plasma
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
