name       : plasma-desktop-branding
version    : 1
release    : 3
source     :
    - git|https://github.com/solus-project/plasma-desktop-branding.git : b60c5f58937a058c57fbbe0a0ef69002ea45f9f0
license    : GPL-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - solus-artwork
patterns   :
    - livecd :
        - /usr/share/sddm
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
