name       : plasma-desktop-branding
version    : 1
release    : 10
source     :
    - git|https://github.com/solus-project/plasma-desktop-branding.git : 5f6e90a5c1a819d4ec3170fd0239149958a922fe
license    : GPL-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - solus-artwork
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
