name       : plasma-desktop-branding
version    : '3.1'
release    : 26
source     :
    - https://github.com/getsolus/plasma-desktop-branding/releases/download/3.1/plasma-desktop-branding-3.1.tar.xz : 2927fdab155863b3cc668c50dda2d71082a9f3fcd6b73aa233e28375c0ae0d29
license    : Apache-2.0
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - font-clear-sans-ttf
    - solus-artwork-plasma
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
