name       : plasma-desktop-branding
version    : 1
release    : 13
source     :
    - git|https://github.com/getsolus/plasma-desktop-branding.git : 98f5cee41e16ffc7c3f5eb8c540a7a66a6d99feb
license    : GPL-2.0-or-later
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - solus-artwork-plasma
    - xdg-desktop-portal-kde
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
