name       : plasma-desktop-branding
version    : '3.2'
release    : 56
source     :
    - git|https://github.com/getsolus/plasma-desktop-branding.git : f5d3b59fdcb8322c85ca61a47b8b7f500e7f8ac2
license    :
    - Apache-2.0
    - LGPL-2.0-only # layout-template
summary    : Defaults for the Plasma Desktop
component  : desktop.kde.core
description: |
    Plasma Desktop Experience Configuration
rundeps    :
    - breeze-cursor-theme
    - breeze-light-cursor-theme
    - breeze-gtk-theme
    - font-clear-sans-ttf
    - solus-artwork-plasma
patterns   :
    - livecd :
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
